### ISSUE TITLE
Strange indentation of Elisp code comments

### ISSUE THREAD

**Issue by peterwvj** [Malabarba/aggressive-indent-mode#100]
I'm experiencing strange issues when I delete the first character of Elisp code comments that start with `;;` using the <kbd>DEL</kbd> key. Similar issues happen if I insert a newline immediately after writing a comment that starts with `;`. The issues are demonstrated using the gif below:

![optimised](https://cloud.githubusercontent.com/assets/5388919/19830291/f77933c2-9df4-11e6-8ba2-5b093cad0d8e.gif)

Note that the `.el` file contains nothing but the code comments.

Unfortunately I can't reproduce this when I launch emacs without loading the init file. So I'm looking for suggestions for how to track this down. If you have any idea about what could be causing these issues then I'm all ears.

I can produce this using the following configuration:

``` elisp
(require 'aggressive-indent)
(global-aggressive-indent-mode 1)
```

Thanks in advance!

**Comment by Malabarba** [comment]
That's just the way that `emacs-lisp-mode` indents comments with a single `;`. They are pushed to column 40 (whereas comments with `;;` are indented relative to the code around them). 
You can reproduce it without aggressive-indent-mode by just hitting `tab` on a line with one of those comments.

**Comment by peterwvj** [comment]
Oh, I see. I'm sorry for the confusion then. Thanks for the explanation.
