### ISSUE TITLE
Conflict with nameless-mode

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/aggressive-indent-mode#106]
Hi there,

I commonly run into cases in which aggressive-indent does its thing in an invisible part of the buffer, before that part has been fontified.  The issue with that is that I use nameless, and thus fontification is relevant to indentation.

The solution could be as simple as running font-lock-ensure on the appropriate region before indenting, but if that's too costly in general there could be a function set to #'ignore by default that nameless would hook into.

Cheers, and thanks for the cool packages!

**Comment by Malabarba** [comment]
That's interesting. I'd never seen Emacs font-lock the buffer *that* lazily.
Aggressive-indent has changed a bit since you posted this issue. If it's still a problem I can look into it.

**Comment by cpitclaudel** [comment]
It's still an issue :)

I sometimes have mismatched parentheses, and these tend to cause reindentation of large bits of the file.  Often these bits aren't syntax-highlighted.

**Comment by Malabarba** [comment]
I'll try adding a variable you can configure to font-lock the buffer, is that ok?

**Comment by Malabarba** [comment]
You should be able to fix your problem by doing: 

```
(add-function :before
              aggressive-indent-region-function
              #'font-lock-ensure)
```
