### ISSUE TITLE
Question: Aggressive Indent inside orgmode codeblock

### ISSUE THREAD

**Issue by Salompas** [Malabarba/aggressive-indent-mode#109]
Hello everyone!
Is it possible to have aggressive indent work inside a code block in orgmode?
For example, you have some text in an orgmode file, and then a code excerpt:

    #+BEGIN_SRC sqlite
    DELETE 
    FROM 
    TABLE 
    WHERE 
    ID=1;
    #+END_SRC
    
The idea is to have aggressive indent work within this source code block, so that we get:

    #+BEGIN_SRC sqlite
    DELETE 
    FROM 
        TABLE 
    WHERE 
        ID=1;
    #+END_SRC

I'm not sure if this is already possible. If it is, could someone point me in the right direction?
Thanks for helping! :D

**Comment by Malabarba** [comment]
Unfortunately, there's no easy way that I know of. 
Org-mode's codeblock are a bit of a dark magic for me.

**Comment by doolio** [comment]
@Salompas @Malabarba If you hit `C-c '` in an org src block this opens a new major-mode edit buffer containing the body of the ‘src’ code block, ready for any edits. Within this buffer `aggressive-indent` will work as you would expect though I don't think it supports sqlite or if it is relevant. Hit `C-c '` again to return to your org buffer. HTH.

**Comment by Salompas** [comment]
@doolio That's actually perfect. A great and easy way to fix all problems related to indenting, and much more. Thanks for that! :D
