### ISSUE TITLE
Eat spaces at the EOL while I'm typing

### ISSUE THREAD

**Issue by Pitometsu** [Malabarba/aggressive-indent-mode#116]
When I type something like `Hello there, folks` at `scala-mode` it eat all the spaces,
and I have `Hellothere,folks`. The only way is `C-b` and put spaces back when them not at the end of line.

**Comment by Malabarba** [comment]
Does `indent-region` also cleanup whitespace in scala-mode?
That would explain the behaviour. The only way in which aggressive-indent-mode ever modifies the buffer is by calling indent-region.

**Comment by Pitometsu** [comment]
Yes, it is. Thank you for suggestion. Seems like it's more `scala-mode` issue, sorry for disturb.

**Comment by Malabarba** [comment]
No problem. Happy to help.
There's probably a config option to disable this in scala-mode.
