### ISSUE TITLE
respect revert-buffer

### ISSUE THREAD

**Issue by CeleritasCelery** [Malabarba/aggressive-indent-mode#124]
When `auto-revert-mode` is enabled, or the buffer is reverted, everything that changed gets added to `aggressive-indent--changed-list`, which means that they will all get reindented when the next command is executed. 

This is particularly an issue when using version control and switching branches. large swatches of buffer are reindented all the time, really polluting the diffs. 

I was able to solve this by clearing `aggressive-indent--changed-list` in `after-revert-hook`, but I am not sure if that is the best solution.

**Comment by Malabarba** [comment]
I think that's a fine solution. Reverting the buffer is a lot like opening a new file. Aggressive indent shouldn't mess with that.

Would you like to submit your change as a PR?

**Comment by CeleritasCelery** [comment]
sure
