### ISSUE TITLE
add it to `before-save-hook` not on the fly

### ISSUE THREAD

**Issue by c02y** [Malabarba/aggressive-indent-mode#42]
Can I use it after saving the file using `C-x C-s`, not indent on the fly:

    (add-hook 'before-save-hook ...)

FYI, do not consider the buffer like `*Scratch*` that is not associated with any file.

**Comment by Bruce-Connor** [comment]
Aggressive-indent only reindents code around point. For this reason, it wouldn't make a ton of sense to indent before saving (that would have to be a more global operation). 

Why do you feel you need this? Are you having performance issues?

**Comment by c02y** [comment]
If I use aggressive-indent-mode on the fly, it will surely cause the performance issues, because it keeping parsing the semantic around the point, but this is not my problem.

Maybe because aggressive-indent-mode provides more power than I want, I simply want format the whole file before-save-hook. I guess I can just defun a new function to do that.

**Comment by Bruce-Connor** [comment]
> If I use aggressive-indent-mode on the fly, it will surely cause the performance issues, because it keeping parsing the semantic around the point, but this is not my problem.

Have you tried, though? It's pretty well optimised and usually the performance hit isn't noticeable. 

> I simply want to format the whole file before-save-hook. I guess I can just defun a new function to do that.

Yes, just write a function that calls indent-region from point-min to point-max. You may also want to wrap that in an ignore-errors.

**Comment by c02y** [comment]
> Have you tried, though? It's pretty well optimised and usually the performance hit isn't noticeable.

I tried month ago, performance is not the problem. 

> Yes, you can write a function that calls indent-region from point-min to point-max. You may also want to wrap that in an ignore-errors.

I already did it in `(add-hook 'before-save-hook..`.

**Comment by Bruce-Connor** [comment]
Sorry for my disappearance. I wasn't notified of your comment for some reason.

I meant that you might want to use ignore-errors (it's a macro, check it out) inside the function that you're adding to before-save-hook. Because indentation commands can sometimes throw errors and that might prevent the buffer from being saved.

But it was just a suggestion, not sure if it's necessary.
