### ISSUE TITLE
How to don't indent after >

### ISSUE THREAD

**Issue by xikky** [Malabarba/aggressive-indent-mode#45]
How can I modify the aggressive-indent-dont-indent-if setting given to also wait to indent until > is pressed on the keyboard.

I would like to have this to stop indentation while writing HTML markup code.

Thank you for such a great package!

**Comment by Malabarba** [comment]
You could use a defvar for that. Something like the following should do:

    (defvar-local waiting-for-> nil)
    (add-to-list 'aggressive-indent-dont-indent-if 'waiting-for->)
    
And then you'll need to make sure your <kbd><</kbd> key calls `(setq waiting-for-> t)` and that your <kbd>></kbd> key calls `(setq waiting-for-> nil)`.

**Comment by xikky** [comment]
Works great! Thank you :)
