### ISSUE TITLE
cursor tarp in clojure-mode

### ISSUE THREAD

**Issue by expez** [Malabarba/aggressive-indent-mode#48]
Be in clojure-mode and let `|` denote the cursor:

```clj
(defn my-fn
| "my docstring
")
```

With the cursor in this position aggressive-indent-mode doesn't allow me to move my cursor using `forward-char`.  I have to use `move-end-of-line` or similar to escape the tarp.

**Comment by Malabarba** [comment]
Coincidentally, I've just pushed a complete rewrite of the aggressive-indent's engine, which should fix this as a side-effect.
Namely, reindentation now only happens after a change, not after every command.
Let me know if it works for you.

**Comment by expez** [comment]
Works like a charm! :+1:
