### ISSUE TITLE
Indent even when region is active.

### ISSUE THREAD

**Issue by mattiasb** [Malabarba/aggressive-indent-mode#5]
When moving code blocks around with the move-text packages aggressive indentation isn't being triggered until I press C-g to clear the mark around my text.

[This youtube-video](https://www.youtube.com/watch?v=Lqa-tspDoVQ) says more than 10³ words though.

I have no idea if this is fixable in a non hacky way or so, if not just close this. :)

Thanks for an awesome package!

**Comment by Malabarba** [comment]
I'll close it as it's unlikely to ever get implemented. In any case, reindentation should happen automatically after the region is deactivated. So the feature is mostly unnecessary.
