### ISSUE TITLE
Wish: Indent only after changes

### ISSUE THREAD

**Issue by egarrulo** [Malabarba/aggressive-indent-mode#50]
Thanks for this useful package!

Aggressive Indent Mode indents code after every command and this can slow down navigation (at least, this is what I experience with some large Emacs Lisp files).  Also, standard Emacs libraries are not indented properly, and just skimming the code of a library can modify the buffer contents, making Emacs prompt for saving when the buffer will be closed.  Therefore, it would be useful to have an option to indent only after modifications.

Thanks for your attention.

**Comment by Malabarba** [comment]
Hey there.
Indenting only after change is already implemented on the unstable version. :-)
It's been on Melpa for about a month now, so it's definitely time to release it as stable. I'll tag it now and it should be on Melpa stable in a couple of hours. If you install from GNU Elpa, it should be up by tomorrow.

**Comment by egarrulo** [comment]
Unfortunately, the new stable version cannot be installed because it depends on Names 20150125.9, whereas Melpa Stable has Names 0.5.4 and Gnu has Names 20150115.1.

Thanks for your attention.

**Comment by Malabarba** [comment]
Ops, sorry about that. I've tagged a more recent Names on melpa stable now. Should be up soon.

**Comment by egarrulo** [comment]
It works now.  Thank you.
