### ISSUE TITLE
Issue with manual commenting in cc-mode derived modes

### ISSUE THREAD

**Issue by sjrmanning** [Malabarba/aggressive-indent-mode#51]
In cc-mode derived modes such as java-mode, the beginning `/` of a comment causes unwanted indentation, e.g.:

![java comment indentation](http://i.imgur.com/GqGXEdZ.gif)

Not sure how possible or easy it is to fix this. Using something like `comment-dwim` gives correct behaviour but I often find myself for whatever reason beginning comments manually and run into this. My elisp abilities are pretty bad so I wasn't able to glean much from `-internal-dont-indent-if` to fix it myself 😕

**Comment by Malabarba** [comment]
Try the following. If it works for you I can add it internally to c-like modes:

   (add-to-list 'aggressive-indent-dont-indent-if '(string-match "^\\s-*/\\s-*$" (thing-at-point 'line)))

**Comment by Malabarba** [comment]
And thanks for the gif :)

**Comment by sjrmanning** [comment]
Ah ha! Nice one, works perfectly :) Thanks so much, and of course thank you for your work on aggressive-indent — one of my favourite packages!
