### ISSUE TITLE
void-variable `aggressive-indent-`

### ISSUE THREAD

**Issue by stardiviner** [Malabarba/aggressive-indent-mode#52]
I use el-get to manage `aggressive-indent-mode`, it always raise this error when I try to update it.
Seems issue related with package `namespaces`.

**Comment by Malabarba** [comment]
I'm not sure how el-get works, but you need to make sure that `names` is loaded before installing `aggressive-indent`. Also note that you need `names` to be loaded before generating autoloads for `aggressive-indent`.

**Comment by Malabarba** [comment]
Did you manage to solve this?

**Comment by stardiviner** [comment]
@Malabarba yes, after add line `(require 'names)` after load el-get. then I can upgrade packages which uses `define-namespace`.
