### ISSUE TITLE
aggressive indent not updating all effected regions

### ISSUE THREAD

**Issue by HParker** [Malabarba/aggressive-indent-mode#53]
![agressive-indent-demo](https://cloud.githubusercontent.com/assets/4482399/9234424/02d5a1b8-40f6-11e5-87f6-ca6ac8aa4fca.gif)

Looks like aggressive indent no longer considers `def goodbye` as being something that should be updated when the parens are closed.

Not sure if this is a ruby mode issue or a aggressive indent mode issue.
calling `M-x indent-region` restores the class to proper indentation.

**Comment by Malabarba** [comment]
Should be fixed now. Thanks for reporting.

**Comment by HParker** [comment]
Thank you for the quick response! will pull the latest form melpa.
