### ISSUE TITLE
[Question] Can aggressive-indent-mode support SQL indent?

### ISSUE THREAD

**Issue by stardiviner** [Malabarba/aggressive-indent-mode#54]
As the title.

I did a search on Google, Emacs Wiki, found some extensions like sql-indent.el.
But it can not work good.

I want to ask the title question.

**Comment by Malabarba** [comment]
Did you turning on `aggressive-indent` in a buffer with sql-indent active?
What happened?

Aggressive-indent just uses the usual indent-region function, which other modes should set according to their needs. So there's no reason why it wouldn't work with sql

**Comment by stardiviner** [comment]
Sorry for execuse, I found the problem is on `sql-indent.el` conflict with my some init settings.
Seems sql-indent + aggressive-indent-mode can work.
