### ISSUE TITLE
aggressive-indent very slow in bigger C functions

### ISSUE THREAD

**Issue by Dickby** [Malabarba/aggressive-indent-mode#57]
Hi,
if I type something in a bigger C function, I have to wait a few seconds to see the changes.
The prefer-defun option not enabled for c-mode (this option seems to slow it down even more in c-mode).
I have it checked with emacs -q and only aggressive-indent-mode enabled.
Thanks

**Comment by Malabarba** [comment]
Unfortunately, there's not much that can be done about that. I'm always open to optimization ideas, but so far I've done all I can think of. =/

In cases where a function is very slow to indent, it can take a couple of seconds. But at least it is done in a way that shouldn't prevent you from typing.

**Comment by Dickby** [comment]
Nevermind,
it's a great package.
Thanks
