### ISSUE TITLE
Can't delete trailing whitespace

### ISSUE THREAD

**Issue by bjeanes** [Malabarba/aggressive-indent-mode#59]
Hi,

Thanks for aggressive indent. It's generally super awesome.

I am having one really annoying issue (most noticeable when editing Ruby files)... When aggressive-indent-mode is enabled, empty lines have trailing whitespace up to the current indent level. I can not delete this trailing whitespace manually or with `whitespace-cleanup`. I have to disable aggressive indent, delete the trailing whitespace, commit the file, and re-enable.

I am on Emacs 24.5 and enable the mode like so:

```
(add-hook 'prog-mode-hook 'aggressive-indent-mode)
```

Let me know if there's any further information I can provide to help here.

**Comment by Malabarba** [comment]
This is definitely a bug to be tackled.
For now, you can probably work around it by adding `#'whitespace-cleanup` to your `before-save-hook`.

**Comment by bjeanes** [comment]
Indeed I usually have such an option configured but in the instance where I ran into this bug, I have to keep it disabled because it cleans up necessary whitespace in multi-line locale strings. I'm in a middle ground of "don't introduce new trailing whitespace" but not "remove all trailing whitespace" :\\

**Comment by Malabarba** [comment]
I see. =/
Well, whitespace-cleanup is quite configurable, so you might still be able to make it behave correctly in these cases. See its docstring for more information.

I've never configured it myself, so I don't know whether it will help or not. =/

**Comment by bjeanes** [comment]
Thanks I'll look into it. Either way, just wanted to bring this bug to your attention. Thanks again for everything!

**Comment by Malabarba** [comment]
I pushed a fix which at least prevents one corner case I experienced in ruby files. Let me know if it fixed your problem.
