### ISSUE TITLE
aggressive-indent-mode sometimes delays handling of keys until next key is typed

### ISSUE THREAD

**Issue by tsdh** [Malabarba/aggressive-indent-mode#62]
Since some time, I sometimes have the situation that I type "foo" but only "fo" is inserted in the buffer.  Then I type SPC and see "foo" but not the space, etc., so the last key is inserted only after the next one has been typed.

This has completely been irreproducible for me but just now I found a recipe, and it seems to be `aggressive-indent-mode`s fault, or maybe `aggressive-indent-mode` triggers a bug inside emacs (current git master and a-i-m from MELPA as of today but I have that problem for several months and update daily).

Ok, here we go.

1. `emacs -Q`
2. `M-x package-initialize`
3. `M-x global-aggressive-indent-mode`
4. `C-x C-f ~/test.sh`
5. Type "if true" but only "if tru" is displayed.  Type `DEL` and then you'll see "if true".  Now move, e.g., with `C-b` and see how the displayed text catches up to "if tru".

Note that it seems to be important what you type.  When I try typing "foo" initially, it all works fine.  It has to be a keyword like "if".  When you use "while" instead, that strange behavior starts after typing the "e", i.e., it starts as soon as you have typed the complete keyword.

Oh, and it is not limited to editing commands.  If after typing the initial "if" I do `C-h f some-function RET` nothing seems to happen.  Only after I type any further key, the window is split and the `*Help*` buffer is shown.

Also, when that wicked behavior started, emacs takes 100% of one CPU core here.

While the recipe is with `sh-mode`, I had this problem several times with `clojure-mode`, too.

**Comment by tsdh** [comment]
Looking at your `post-command-hook` function, I suspect the problem is in `while-no-input`.

**Comment by tsdh** [comment]
Indeed, here is a minimal recipe for triggering the problem without `aggressive-indent-mode`.

```elisp
(defun th/loop-on-no-input ()
  (while-no-input (while t t)))

(add-hook 'post-command-hook #'th/loop-on-no-input)
```

I'm closing this bug and open a new one for Emacs.

**Comment by tsdh** [comment]
For reference:http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21747

**Comment by Malabarba** [comment]
Thanks for tracking this down Tassilo. I've noticed this too on a number of occasions. 
Maybe I'll try to use the sit-for call in Eli's example, or maybe I'll just call redisplay before starting the loop.

**Comment by tsdh** [comment]
You're welcome.  IMHO, `while-no-input` should cater for this issue itself, e.g., by calling `sit-for` before executing `body`.  But of course that won't help with this issue for emacsen < 25.1.
