### ISSUE TITLE
Clojure cond has problems with aggressive-indent-mode

### ISSUE THREAD

**Issue by arichiardi** [Malabarba/aggressive-indent-mode#63]
A picture is worth a thousand words:

![selection_008](https://cloud.githubusercontent.com/assets/1724788/11199496/e729a378-8c82-11e5-8def-6228ec50eadc.png)

The `:else` clause is placed in the wrong place (and of course I cannot move it unless I disable the mode).

**Comment by Malabarba** [comment]
@arichiardi hi there. 
That's just a general Emacs bug with indentation of lisp modes. But it's fixed on the latest clojure mode.

**Comment by arichiardi** [comment]
:+1:
