### ISSUE TITLE
please use kbd rather than embedding literal control characters

### ISSUE THREAD

**Issue by bremner** [Malabarba/aggressive-indent-mode#64]
Embedded control characters confuse all kinds of tools (e.g. file).
(kbd "C-c C-q") ought to do the trick for the one instance I saw.

**Comment by Malabarba** [comment]
Could you give an example of what problem you had?

**Comment by bremner** [comment]
It causes all kinds of false alarms in debian packaging tools. Any reason to avoid kbd? it seems rather more idiomatic.

**Comment by Malabarba** [comment]
There's no reason to avoid it, I was just wondering what caused a problem for you as Emacs tends to handle these characters quite gracefully. I understand it now, and it'll soon be fixed (probably in #65).
