### ISSUE TITLE
When same buffer is splitted and moved, pointer jumps to other window

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/aggressive-indent-mode#67]
Open a file with many lines and indentation for the proper programming language.
Then split the same buffer into two windows. Scroll around with the buffer in one window.

Then type somewhere fast. The pointer will jump to the other window on another line, and then continues with inserting text. This bug belagued me a lot lately. I have no modifications to Aggressive-indent or evil. Just plain config.

I hope the information above is clear enough for reproduction?

**Comment by Malabarba** [comment]
Yes, I think that was a clear explanation. I have a couple of guesses of what could cause this, but I'll only be able to look into it in a few days.

**Comment by ReneFroger** [comment]
I hope your relocation going well. Already settled in your new place? :+1: And did you have any chance to look into this? Perhaps I could deliver a screencast, if you wasn't able to reproduce this.

**Comment by Malabarba** [comment]
Yes, everything went well. But with family and the holidays, I haven't been able to look into this yet.
I'll try to do it soon.

**Comment by ReneFroger** [comment]
Any update on this? :yum:

**Comment by Malabarba** [comment]
Ok. I've finally fixed this bug locally, but I won't be able to push the fix  until the other week. 
I can tell you how to fix it locally if it's urgent for you.

**Comment by ReneFroger** [comment]
No need for that. I will look forward to the MELPA update.

And wish you all the luck with settling in your new home.

**Comment by ReneFroger** [comment]
Now I get curious about your fix :smiley: , because this bug is bothering me a lot, especially when I use many windows when editing a large buffer.

**Comment by Malabarba** [comment]
I just added a save-excursion and a save-selected-window to the function aggressive-indent--indent-if-changed

**Comment by ReneFroger** [comment]
Hmmz, I still get belagued with the same bug. Nevermind, I will wait until the MELPA update. :+1:

**Comment by ReneFroger** [comment]
Hmmz, I still get belagued with the same bug after adding `(save-excursion)` and `(save-selected-window)` inside the function `(aggressive-indent--indent-if-changed)`, above the  `(when aggressive-indent--changed-list`.  Nevermind, I will wait until the MELPA update. :+1:

**Comment by Malabarba** [comment]
Ok, I've pushed the aforementioned fix. However, if that doesn't fix it for you, feel free to reopen the bug.
