### ISSUE TITLE
Exclude aggessive-indent-mode in .dir-locals.el

### ISSUE THREAD

**Issue by arichiardi** [Malabarba/aggressive-indent-mode#68]
Hello! I tried the following, but it does not seem to work..

```
((nil . ((eval . (push 'clojure-mode live-ignore-whitespace-modes))
          (eval . (add-to-list 'aggressive-indent-excluded-modes 'clojure-mode)))))
```

...maybe because something does not "refresh" after the `add-to-list` inside `.dir-locals.el` triggers. My experience with elisp is also limited so I might miss some better approach...I just followed the line above and the README example in order to exclude `clojure-mode` only for this dir/project...

What am I doing wrong?

**Comment by Malabarba** [comment]
Indeed, I don't think that's going to work. `aggressive-indent-mode` is already active when Emacs reads the local variables, so excluding modes will have no effect.
You could do this instead:


    ((clojure-mode . ((eval . (aggressive-indent-mode -1))))
     (nil . ((eval . (push 'clojure-mode live-ignore-whitespace-modes)))))

**Comment by arichiardi** [comment]
Yes! It looks like it works like that! I am closing and thanks.
