### ISSUE TITLE
Indent on paste

### ISSUE THREAD

**Issue by bbatsov** [Malabarba/aggressive-indent-mode#72]
One great addition for agressive-indent-mode would be to reindent the code after certain paste operations e.g. `C-y`.

**Comment by Malabarba** [comment]
It should already do that, no? Aggressive-indent reindents after every change, so it's supposed to work with any kind of pasting.

**Comment by bbatsov** [comment]
Well, it doesn't. When I paste something my code is not indented properly until I do something else in the buffer to trigger aggressive-indent.

**Comment by Malabarba** [comment]
Oh, you're right. :-)
Now I remember I disabled this because I was afraid it might break `M-y`. Don't know if I ever actually tested it though.

**Comment by Malabarba** [comment]
Wait. I retract my previous statement. I think removed that clause some time ago.
`C-y` for me does cause indentation. Do you have an example in which it doesn't for you?

**Comment by bbatsov** [comment]
Any paste I do doesn't do indentation. I'll create some repro steps.

**Comment by zw963** [comment]
C-y indent in emacs-lisp-mode worked for me. 

emacs 24.5, test with only following config:
```cl
(require 'aggressive-indent)
(global-aggressive-indent-mode 1)
```

**Comment by Malabarba** [comment]
@bbatsov still having this problem?
