### ISSUE TITLE
Request to delay the indentation until a non-kill/non-edit command

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/aggressive-indent-mode#76]
I heavily make use of the emacs feature where consecutive kills using any kill command get clubbed into one text block.

For example:

```el
(let ((a 1)
      (b 2)
      (c 3)))
```

With `aggressive-indent-mode` disabled and cursor before `(a` in the above snippet, I can do `C-M-k C-M-k C-M-k` to kill the `a`, `b`, `c` let bindings. Now when I do `C-y`, the below gets pasted:

```el
(a 1)
(b 2)
(c 3)
```

But with `aggressive-indent-mode` enabled, after each `C-M-k`, re-indentation happens and that step breaks the chain of consecutive kill commands. So doing `C-M-k C-M-k C-M-k C-y` pastes just `(c 3)`. I know that I can prevent this from happening if I do `C-u 3 C-M-k C-y`. But in that case I need to mentally calculate how many forms I need to kill in advance.

I hope there's an easy enough fix for this.

Thank you.

**Comment by Malabarba** [comment]
That's odd. I don't have that problem. Are you sure it's being caused by aggressive-indent?

The way the kill commands work is that they check the value of `last-command`. Aggressive-indent's indentation should not affect that variable at all.

**Comment by kaushalmodi** [comment]
> That's odd. I don't have that problem. 

What's even more odd is that even I now cannot recreate that problem :)

> Are you sure it's being caused by aggressive-indent?

Yes. Because I had to toggle off aggressive indent in emacs-lisp-mode each time I needed to do those consecutive kills. I had to do that at least 10 times in last 2/3 weeks and so got pushed to write this bug report :P

> The way the kill commands work is that they check the value of last-command. Aggressive-indent's indentation should not affect that variable at all.

OK. I thought that the auto-indentation done by aggressive-indent-mode got set as last-command and thus broke the consecutive kill chain. But you are right; I spent last 10-15 minutes trying to recreate this bug with aggressive-indent-mode in a fresh emacs session and I am unable to.

I attempted to do everything so that almost all packages in my config get autoloaded, loaded every major mode I use everyday, etc. but that bug just won't reappear. I know what to do next time.. I will get a list of all minor modes enabled next time this issue occurs and will also edebug aggressive-indent-mode to get to the root of this. When I have seen this bug occur, it had stayed that way consistently, so I should get enough time to debug this.

Will keep you posted.

**Comment by kaushalmodi** [comment]
I'll close this issue for now, until I get some concrete debug info. I haven't yet been able to recreate the bug. So chances are that something got fixed in emacs-25 branch or org master branch, or one of the packages that got updated today ... or this bug shows up only after a full day's of emacs session, don't know :)

**Comment by Malabarba** [comment]
Sounds like a plan!
