### ISSUE TITLE
Version 1.5.2 breaks ielm

### ISSUE THREAD

**Issue by spwhitton** [Malabarba/aggressive-indent-mode#79]
Steps to reproduce:

1) Install version 1.5.2 (I've not test 1.5.1)
2) `M-x ielm M-x aggressive-indent-mode`
3) type `(`

Expected result:

`(` with point after the `(` character

Actual result:

`(` with point before the `(` character, and an error message instead of a `)` if using paredit or electric-pairs.

**Comment by Malabarba** [comment]
Is this still also an issue on the latest version?

**Comment by spwhitton** [comment]
It isn't -- thanks.
