### ISSUE TITLE
Version 1.5.2 breaks paredit: point jumps around

### ISSUE THREAD

**Issue by spwhitton** [Malabarba/aggressive-indent-mode#80]
Steps to reproduce

1) Open an Emacs Lisp file
2) M-x aggressive-indent-mode
3) M-x paredit-mode (version 24)
4) Add the following code:

    ;;; IELM
    
    ;; (setq ielm-dynamic-return nil)
    
    ;;; text mode
    
    (add-hook 'text-mode 'turn-on-auto-fill)
    (diminish 'auto-fill-function)
    ;; (add-hook 'text-mode 'refill-mode)

5) Put point at the end of "IELM" and press RET.

Expected result:

    ;;; IELM
    <point>
    
    ;; (setq ielm-dynamic-return nil)
    
    ;;; text mode
    
    (add-hook 'text-mode 'turn-on-auto-fill)
    (diminish 'auto-fill-function)
    ;; (add-hook 'text-mode 'refill-mode)

Actual result:

    ;;; IELM
    
    
    ;; (setq ielm-dynamic-return nil)
    
    ;;; text mode
    
    <point>(add-hook 'text-mode 'turn-on-auto-fill)
    (diminish 'auto-fill-function)
    ;; (add-hook 'text-mode 'refill-mode)

**Comment by Malabarba** [comment]
Could you try the latest version? It's 1.5.3.

**Comment by spwhitton** [comment]
It works.  I'm looking forward to the release :)  Thanks for your feedback and efforts.

**Comment by Malabarba** [comment]
1.5.3 should be on Gnu Elpa already. :-)

**Comment by spwhitton** [comment]
@Malabarba could you tag a release here on github, please?

**Comment by Malabarba** [comment]
To be honest, I'm half inclined to remove tags altogether here. It's redundant to have stable releases both on Gelpa and Melpa stable, and keep forgetting to update one of them whenever I update the other. 

I haven't decided on that yet, though.

**Comment by spwhitton** [comment]
That's fair enough.  Are you definitely going to keep uploading new versions to GNU ELPA?  If that's so, I'll switch the Debian packaging over to that.

**Comment by Malabarba** [comment]
Yes. That's the plan. 

I probably won't remove the tags so soon, so you don't have to change if you think it's too much work. Just keep in mind I might forget to tag it once in a while. 😁
