### ISSUE TITLE
Add indent delay.

### ISSUE THREAD

**Issue by zw963** [Malabarba/aggressive-indent-mode#81]
Thanks for this aggressive-indent-mode, it save my life about frequently invoke shortcut
about `format-buffer` things.

But, this seem like too greedy, it indent frequency is too high for me.
e.g. in Ruby mode, a  `,`(less than one second) will cause many code
 behide this comma greedy reindent.

I thought if can set a threshold, e.g. 1.5 seconds, it more comfortable.

**Comment by Malabarba** [comment]
I'm planning on adding an option that only reindents before saving the file. Do you thing that would suit your use-case?

**Comment by zw963** [comment]
Add after save indent function is good, though well could simple write a `format-buffer` function,
and add this function to `after-save-hook` by myself.

But i think this could not replace editing indent,  I just hope this mode don't be so aggressive.

**Comment by Malabarba** [comment]
Another option is to simply not reindent if the line ends in a `, `. There's a variable called `aggressive-indent-dont-indent-if`.

**Comment by zw963** [comment]
This hack should work, thanks.

Though, if support `REGEXP` directly is more simple for me.

I hope, only aggresssive indent when input [A-Za-z] is enough.

anyway, here some code from `auto-indent-mode`,  hope could 
help a little about add a delay time for indent.

https://github.com/mattfidler/auto-indent-mode.el/blob/master/auto-indent-mode.el#L987-L1004

**Comment by Malabarba** [comment]
Thanks. I'll look into it if I try to implement the feature.

**Comment by oscarfv** [comment]
While editing Lisp code on a netbook (hence, a "slow" machine by current standards) if the function has more than about 12 lines and you write quickly, aggressive indent sometimes gets in the way: Emacs beeps and some keystrokes are ignored. Introducing a delay could solve this problem but I'm worried about the possibility of the user moving moving the cursor to another place and aggressive indent ignoring the text chunk that was previously edited. Maybe it needs to track the points where the edition happens and then indent those chunks.

**Comment by Malabarba** [comment]
> Maybe it needs to track the points where the edition happens and then indent those chunks.

It already does that. And it tries to be very quiet while indenting, so I'm really surprised you get beeps.

**Comment by Malabarba** [comment]
There's now a custom-option for configuring the delay. See `aggressive-indent-sit-for-time`

**Comment by oscarfv** [comment]
Thank you. I'll try it.
