### ISSUE TITLE
Disable electric-indent-mode in ruby-mode?

### ISSUE THREAD

**Issue by zw963** [Malabarba/aggressive-indent-mode#82]
Ohh, I update to emacs 24.5 recent days, feel `electric-indent-mode` is cool.

it worked better than old `(reindent-then-newline-and-indent)`, But it disable
by this mode, Is there any conflict with this?

**Comment by Malabarba** [comment]
Yes.  Electric indent mode sometimes causes conflicts with aggressive indent. Besides, everything that electric indent offers is already covered by aggressive-indent-mode, so there's no need to use both.

**Comment by zw963** [comment]
Except `RET` default binding is restore to `newline`, in some case, it worked well with
`auto-indent-mode` Textmate like `meta-return`.

https://github.com/mattfidler/auto-indent-mode.el/blob/master/auto-indent-mode.el#L1669-L1678

**Comment by Malabarba** [comment]
I'm sorry, I didn't understand. What is the feature offered by electric-indent that isn't covered by aggressive indent?

**Comment by zw963** [comment]
textmate like `meta-return`, basically is 
```cl
(move-end-of-line)
(newline)
```
the problem is:
When electric-indent is open, this newline is auto-indent.
But, for now, it not auto-indent.

e.g.

```ruby
# cursor after `h`
def h|ello
end
```
if press `meta-return`,  correct result should be:
```el
  def hello
     |
   end
```
But for now:
```ruby
  def hello
|
  end
```

I think the main problem is: 
this package unexpected change old `kbd "RET"` behavior.

As following code in previous example:
``(call-interactively (auto-indent-original-binding (kbd "RET")))``

**Comment by zw963** [comment]
But, this not a big things, I could binding meta-return myself to a self defined function,
in this function, use 

```cl
(move-end-of-line)
;;  change `newline` to `newline-and-indent`.
(newline-and-indent)
```
That is what i did before emacs 24.4 (with electric-indent-mode)

The key is some behavior have been tested work well before,
and suddenly not worked.  spent some times to find out where
and what is changed cause this.

**Comment by Malabarba** [comment]
Still. If you just start typing on that empty line aggressive-indent will indent it for you, won't it?

**Comment by zw963** [comment]
> If you just start typing on that empty line aggressive-indent will indent it for you, won't it?

Yes. I think this is no need fixed now,  Thanks for help.

**Comment by zw963** [comment]
Though, I still hope can correct indent even not typing on this empty line.
