### ISSUE TITLE
backward delete word in ruby-mode cause keyboard quit in emacs 24.5

### ISSUE THREAD

**Issue by zw963** [Malabarba/aggressive-indent-mode#83]
`Alt+DEL` work not well.
 `Del`  `Kill Line` work not well too in some mode.

when execute those keybinding,  will invoke `keyboard-quit` like operation.

following is a example, When in ruby-mode, press Alt+Del.

![](https://zw963.github.io/recorded10627660.gif)

**Comment by Malabarba** [comment]
If you're referring to `backward-kill-word`, then I'm afraid can't reproduce this. =/
Looks like there's something else going on in your buffer. While is the screen flashing black like that?

**Comment by zw963** [comment]
> Why is the screen flashing black like that?

because I settings like this:
```cl
(setq visible-bell t)
```

**Comment by Malabarba** [comment]
Hm. Then something is ringing the bell.
Try enabling `debug-on-quit` with `M-x toggle-debug-on-quit`.

When you reproduce the issue, does a backtrace show up?

**Comment by zw963** [comment]
> If you're referring to backward-kill-word, then I'm afraid can't reproduce this

Why always my problem can not reproduce ...

My test is only little dotfiles which relative to this package is used. 

following is all my produce for this:

![recorded2880714111.gif](http://zw963.github.io/recorded2880714111.gif)


in this case, all my dotfiles is:

```cl
(add-to-list 'load-path "...")
(setq visible-bell t)
(require 'aggressive-indent)
(global-aggressive-indent-mode 1)
```
And then, open 1.rb files, `backward-kill-word`.

Does you test this like me with `emacs -Q`?

And i test in MInt 17.3 and openSUSE 42.1, it not emacs problem.

**Comment by Malabarba** [comment]
> Try enabling debug-on-quit with M-x toggle-debug-on-quit.

I'm sorry,  I meant `M-x toggle-debug-on-error`

**Comment by zw963** [comment]
> I'm sorry, I meant M-x toggle-debug-on-error

No any error, just like `C-g`, `keyboard-quit`.

**Comment by zw963** [comment]
I get ride of all others factor which could affect emacs/this mode.

Add this mode, broken, remove this mode, all worked fine.

I am so wired why you could not reproduce this ... : (

**Comment by Malabarba** [comment]
I just pushed a change that might affect this. Could you try the latest master?

**Comment by zw963** [comment]
Not fixed.

**Comment by Malabarba** [comment]
Then I don't know what could be causing this. :-(
I followed all the same steps in your screencast (using the current master branch) and nothing unusual happened.

**Comment by zw963** [comment]
Sorry, It seem like work well for emacs 24.3  (with-x-toolkit=gtk2, default version)

But, current, I used compile 24.5 (with-x-toolkit=lucid).

it happen those strange things ...

Could you please have a try?

**Comment by zw963** [comment]
my configure is
```sh
./configure \
    --without-gconf \
    --without-gsettings \
    --with-x \
    --with-x-toolkit=lucid
```

maybe you will need following package to make compile succss.

sudo apt-get install -y libxaw7-dev libncurses5-dev libjpeg-dev \
        libgif-dev libtiff-dev

**Comment by zw963** [comment]
Seem like not caused by '--with-x-toolkit=lucid` things.

becase when I create this issue, I use openSUSE, i used
system preinstall version (gnome version emacs)

**Comment by Malabarba** [comment]
what's the emacs version that comes preinstalled with gnome?

**Comment by zw963** [comment]
> what's the emacs version that comes preinstalled with gnome?

24.3.1

But, in openSUSE, I have install unofficial 24.5 emacs package.(precompiled)
And, cause this issue happen. so i create this issue.

After switch to Mint, I compile emacs 24.5 myself, error still happen.

**Comment by zw963** [comment]
emacs 24.4 introduce in improved electric-pair-mode and electric-indent-mode.

Maybe this mode conflict with some package.

**Comment by zw963** [comment]
Hi, @Malabarba , does you reproduce this issue in emacs 24.5 ?

**Comment by Malabarba** [comment]
No, sorry. =/
Just tested it on 24.5 and I don't see anything out of the ordinary.

**Comment by zw963** [comment]
Does you enable this: ``(setq visible-bell t)`` ?

**Comment by zw963** [comment]
I am so werid why two package from you exist some issue which could not reproduce from me.

Do you remenber `(smart-mode-line)` the [issue](https://github.com/Malabarba/smart-mode-line/issues/179) which change my `(delete-selection-mode)` to false?  i have to reenable this mode at the end of my dotfiles.

I hope we can find out you or me exist some special case?

could you please give me some gif animal for the entire process?

please ensure to test this with `emacs -Q` to skill any local vendor elisp package.

**Comment by davidshepherd7** [comment]
Hi, I don't know if this is any help but I can't reproduce this with emacs 24.5 compiled with `./configure --with-x-toolkit=lucid` on Ubuntu 15.04 and the latest melpa version of aggressive-indent. I'm running emacs -Q with the code initialisation code you provided.

**Comment by zw963** [comment]
@davidshepherd7 , you try in ruby-mode and press `Alt+DEL` ?

**Comment by davidshepherd7** [comment]
Yeah in ruby-mode and pressing `Alt+DEL`. I don't have a version compiled with `--without-gconf` or `--without-gsettings` though, so maybe you could try without those enabled? Otherwise I don't have any ideas.

**Comment by zw963** [comment]
>> I don't have a version compiled with --without-gconf or --without-gsettings though, so maybe you could try without those enabled?

I recompile emacs 24.5 in Mint 17.3, Not worked for me. : (

@davidshepherd7 , Does you settings `(setq visible-bell t)`?

the full config is:
```cl
(add-to-list 'load-path "...")
(setq visible-bell t)
(require 'aggressive-indent)
(global-aggressive-indent-mode 1)
```

**Comment by davidshepherd7** [comment]
Yeah I ran that code.

I don't have any ideas really. I thought I might be able to reproduce it because I had a build of emacs with lucid and v24.5 on a similar OS to you, but no such luck.

Maybe try reproducing it on a completely separate computer?

**Comment by zw963** [comment]
@Malabarba , Sorry, I found in current master 5959b48, this bug is fixed now. : )

Thanks, Nick to know I could try this mode again ...

**Comment by Malabarba** [comment]
Great. Glad it's fixed.
