### ISSUE TITLE
latest version a definition void

### ISSUE THREAD

**Issue by stardiviner** [Malabarba/aggressive-indent-mode#85]
The function `aggressive-indent--check-parens` is void.

**Comment by seagle0128** [comment]
I got the same error:
`aggressive-indent-mode: Symbol's function definition is void: aggressive-indent--check-parens`
Please fix it ASAP. Thanks!

**Comment by Malabarba** [comment]
It was fixed yesterday before the issue was reported. Just update.  :-):-)
