### ISSUE TITLE
Set Indent Width

### ISSUE THREAD

**Issue by gigavinyl** [Malabarba/aggressive-indent-mode#86]
For some reason, I cannot for the life of me figure out how to set the indent width of this package to 2 spaces. The part of my `~/.spacemacs` config pertaining to tab widths is:
```emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq indent-line-function 'insert-tab)
  (setq-default js2-tab-width 2)
  (setq indent-line-function 'insert-tab)
```

**Comment by Malabarba** [comment]
Aggressive-indent-mode simply follows the indentation style of the major mode. I.e., it reproduces what you would get by hitting tab on each line. 

I think this is a question for js2-mode or maybe spacemacs.

**Comment by gigavinyl** [comment]
@Malabarba The issue happens in Emacs-Lisp mode as well though.

**Comment by Malabarba** [comment]
Same thing. :-)
Does the issue happen if you disable aggressive-indent-mode and just indent by hitting TAB?

**Comment by gigavinyl** [comment]
This config solved the issue :)
```emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq-default js2-basic-offset 2)
```
