### ISSUE TITLE
Aggressive Indent Mode impacts ability to type spaces in Scala files

### ISSUE THREAD

**Issue by randre03** [Malabarba/aggressive-indent-mode#87]
In my Emacs setup I have Aggressive Indent Mode turned on always and I noticed when trying to write my first `.scala` file that I was not able to type a space in between the first and second words (or anywhere)...the cursor would quickly jump back to line up with the end of the last character of the prior word. Sometimes I could type a space with some combination of C/M/SPC but that was not reliable nor desirable. 

I narrowed the cause down and once I turned Aggressive Indent Mode off I am able to type in `.scala` files without trouble. Right now I get around the issue by including `scala-mode` in `'aggressive-indent-excluded-modes`.

This occurred in Emacs 24.5 and 25.1

**Comment by Malabarba** [comment]
Odd. Does Scala mode perform some kind of whitespace cleanup during indentation?

**Comment by randre03** [comment]
I am not an expert on `emacs-scala-mode` but it appears that https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-indent.el is entirely about indenting and spacing.

**Comment by Malabarba** [comment]
Ok. sorry for the late response. I looked into it and it seems that scala mode indeed cleans-up whitespace on purpose in some situations (when the previous line doesn't end in a `;`) and that's what causes this issue. There might be a way for you to disable that, but that's something you'll have to ask them. For now, the only I thing I can do on our side is to  disable aggressive-indent for scala-mode.
