### ISSUE TITLE
Support languages where indentation is not absolute (python, haskell, cofee, etc)

### ISSUE THREAD

**Issue by huseyinyilmaz** [Malabarba/aggressive-indent-mode#9]
Hello, I would like to report a bug that I can reproduce on python mode.
here is the steps to reproduce python the bug.
* start with aggresive-indent-mode disabled
* write following sample code
```
def fun1(a, b):
    return (a, b)


def fun2(a, b):
    value = {'a': a,
             'b': b,
             }
    value2 = fun(a,
                 b)
    return value, value2

```
The problem here is the function call fun(a, b) should be fun1(a,b)

* enable aggresive-indent-mode
* change fun function call with fun1.
* At this moment aggresive-inden-mode changes the code to this.

```
def fun1(a, b):
    return (a, b)


def fun2(a, b):
        value = {'a': a,
                 'b': b,
                 }
                value2 = fun1(a,  # function fun should be fun1
                              b)

                return value, value2
```

Which is not a valid document.

And I see that aggresive-indent mode is forcing whole document to change indentation. I imagined it would change only the secition of the file.

Thanks.
By the way this is an awsome idea.

**Comment by bbatsov** [comment]
I think this ticket can be closed.

**Comment by Malabarba** [comment]
Yeah. One year later and I'm no closer to a solution.

**Comment by unhammer** [comment]
I think you could

     (add-to-list 'aggressive-indent-excluded-modes 'haskell-interactive-mode)

as default as well

**Comment by Malabarba** [comment]
Done
