### ISSUE TITLE
The package does note work well with user added `before-save-hook`

### ISSUE THREAD

**Issue by mrkkrp** [Malabarba/aggressive-indent-mode#90]
Say I have two hooks like so:

```elisp
(add-hook 'before-save-hook #'whitespace-cleanup)
(add-hook 'before-save-hook #'mk-single-empty-line)
```

But when I edit a file where `aggressive-indent-mode` is enabled my customization has no effect. In fact, `before-save-hook` has this value:

```elisp
aggressive-indent-mode ⇒

(aggressive-indent--proccess-changed-list-and-indent t)
```

Is there some why to allow my clean up functions run when `agressive-indent-mode` is enabled?

**Comment by Malabarba** [comment]
That's the buffer-local value of the variable. Your functions were added to the global value and should still be there. Just do C-h v to describe the hook and you'll see what I mean. 
When a hook is run, both the local and global values are run.

**Comment by mrkkrp** [comment]
It doesn't seem to be the case. The global value is ignored, so only local value is run.

**Comment by Malabarba** [comment]
How did you confirm that? Try running the following:

    (add-hook 'before-save-hook (lambda (&rest _) (message "I was called!")))

Do you see a message when you save the file.

**Comment by mrkkrp** [comment]
OK, seems it originates from somewhere else. Closing, sorry for the noise.

**Comment by Malabarba** [comment]
No problem
