### ISSUE TITLE
global-hl-line-mode blinks with aggressive-indent-mode

### ISSUE THREAD

**Issue by Dickby** [Malabarba/aggressive-indent-mode#91]
If global-hl-line-mode and aggresssive-indent-mode is enabled, the highlighted line blinks at every inserted character.
This doesn't happen if I enable hl-line-mode locally.

**Comment by Malabarba** [comment]
I can't reproduce that here. Could you provide a minimal example?

**Comment by Dickby** [comment]
I realized it happens not in every buffer, but for example in C code files.
I use emacs 95.0.95.
This produces the  blinking:

I start with  `emacs -Q` and open a new .c file

M-x package-initialize,
M-x global-hl-line-mode,
M-x aggressive-indent-mode

insert a new line with <enter>
cursor back to first line with C-p
if I now start to type the highlighted line blinks.
M-x hl-line-mode
and the blinking stops

**Comment by Malabarba** [comment]
Odd. And what's your aggressive-indent version?

**Comment by Dickby** [comment]
the version is 20160608.1625

**Comment by Dickby** [comment]
I solved this just by enabling hl-line-mode in the c-mode-hook that enables aggressive-indent-mode. But it would be nicer without this hack.

**Comment by Malabarba** [comment]
This could be a performance issue. Unfortunately, I still can't reproduce it. :-(
