### ISSUE TITLE
conflict with evil-mode

### ISSUE THREAD

**Issue by Dickby** [Malabarba/aggressive-indent-mode#98]
I know that aggressive-indent is not meant to work with evil-mode, but till last update it was working ok (just a few places where I had to indent manually).
But since the last update, the aggressive-indent-protected-commands are ignored if evil-mode is enabled.
That makes aggressive-indent in combination with evil-mode unusable.

It would be nice if this could be fixed.
Thanks

**Comment by Malabarba** [comment]
I really don't see how `aggressive-indent-protected-commands` could have changed in the last update. Nothing changed in that area of the code. Maybe evil-mode somehow controls the value of `last-command`?

**Comment by Dickby** [comment]
there are a few '(let (last-command ...))' parts in evil.
Is it possible that this is the reason?
did the last change of aggressive-indent made this possible?

**Comment by Malabarba** [comment]
maybe. The latest change moved aggressive-indent from a post-command hook to an idle timer. That could have some weird interaction with evil if they do some unusual wrapping on commands. Try hacking some aggressive-indent functions to print `(message "%S" last-command)`. Maybe you just have to change the commands you've configured in `aggressive-indent-protected-commands`

**Comment by Dickby** [comment]
The last commit solved this problem.
Thanks a lot!

**Comment by Malabarba** [comment]
Great!
